# Generated by Django 5.0.2 on 2024-02-19 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=6)),
                ('Type', models.CharField(max_length=6)),
                ('RAM', models.IntegerField(max_length=6)),
                ('Battery', models.IntegerField(max_length=6)),
                ('FrontCamera', models.IntegerField(max_length=6)),
                ('date_of_release', models.DateField(auto_now=True)),
                ('company', models.CharField(max_length=100)),
                ('screen_height', models.IntegerField(max_length=6)),
                ('screen_width', models.IntegerField(max_length=6)),
                ('weight', models.IntegerField(max_length=6)),
                ('img', models.ImageField(default='', upload_to='static/')),
                ('color', models.CharField(max_length=6)),
                ('fingerprintSensor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('device_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.device')),
                ('generation', models.IntegerField(max_length=6)),
                ('ssd', models.IntegerField(max_length=6)),
                ('ports', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('graphicscard', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('device_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.device')),
                ('processor', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('rareCamera', models.IntegerField(max_length=6)),
                ('refreshState', models.IntegerField(max_length=6)),
                ('screenType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('user_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.user')),
                ('description', models.CharField(max_length=200)),
                ('rating', models.IntegerField(max_length=100)),
                ('device_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='firstapp.device')),
            ],
            options={
                'unique_together': {('user_id', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('user_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.user')),
                ('device_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='firstapp.device')),
            ],
            options={
                'unique_together': {('user_id', 'device_id')},
            },
        ),
    ]
