# Generated by Django 5.0.2 on 2024-02-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_device_laptop_mobile_review_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='company',
            new_name='manufacturer',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('company_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.company')),
                ('companyName', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('marketValue', models.IntegerField(max_length=6)),
                ('YearOfEstablishment', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='device_id',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='firstapp.device'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_id', 'device_id')},
        ),
    ]
