# Generated by Django 5.0.2 on 2024-03-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_wishlist_user_id_alter_review_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='device_id',
            new_name='devic_id',
        ),
        migrations.AlterField(
            model_name='device',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
