# Generated by Django 5.0.2 on 2024-03-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_rename_device_id_mobile_devic_id_alter_device_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='devic_id',
            new_name='device_id',
        ),
    ]
