# Generated by Django 5.0.2 on 2024-03-28 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_rename_devic_id_mobile_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='img',
            field=models.ImageField(upload_to='pics', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
