# Generated by Django 5.0.2 on 2024-03-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_device_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='device_id',
        ),
        migrations.AddField(
            model_name='mobile',
            name='Device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
