# Generated by Django 5.0.2 on 2024-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_remove_mobile_device_id_mobile_device_mobile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='processor',
        ),
        migrations.AddField(
            model_name='device',
            name='processor',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
