# Generated by Django 5.0.2 on 2024-03-28 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_alter_device_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='img',
            new_name='backsideimg',
        ),
        migrations.AddField(
            model_name='device',
            name='frontsideimg',
            field=models.ImageField(default=0, upload_to='pics/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
