# Generated by Django 5.0.2 on 2024-03-28 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_rename_img_device_backsideimg_device_frontsideimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='refreshState',
            new_name='refreshRate',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='device_id',
        ),
        migrations.AddField(
            model_name='laptop',
            name='Device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstapp.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='backsideimg',
            field=models.ImageField(upload_to='pics/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='device',
            name='frontsideimg',
            field=models.ImageField(upload_to='pics/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen_height',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen_width',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='weight',
            field=models.FloatField(max_length=6),
        ),
    ]
