# Generated by Django 5.0.2 on 2024-03-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_rename_refreshstate_mobile_refreshrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='marketValue',
            field=models.IntegerField(max_length=26),
        ),
    ]
