# Generated by Django 5.0.2 on 2024-03-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_alter_companyinfo_marketvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='rareCamera',
            new_name='rearCamera',
        ),
    ]
