# Generated by Django 5.0.2 on 2024-03-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_rename_rarecamera_mobile_rearcamera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
