# Generated by Django 5.0.2 on 2024-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_alter_device_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Storage',
            field=models.IntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
