# Generated by Django 5.0.2 on 2024-03-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_device_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Battery',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='FrontCamera',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='RAM',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='Storage',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='generation',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='rearCamera',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='refreshRate',
            field=models.CharField(max_length=6),
        ),
    ]
