# Generated by Django 5.0.2 on 2024-03-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_alter_device_battery_alter_device_storage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
