# Generated by Django 5.0.2 on 2024-03-30 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_wishlist_id_alter_wishlist_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user_id', 'device_id')},
        ),
    ]
